---
name: Auto-deployment of uk_cross_government_metadata_exchange_model Documentation
on:
  push:
    branches: 
      - main
      - linkml

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # otherwise, you will failed to push refs to dest repo

      - name: Set up Python 3.
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install Poetry.
        uses: snok/install-poetry@v1.3

      - name: Install dependencies.
        run: poetry install -E docs

      - name: Build documentation.
        run: |
          mkdir -p docs
          touch docs/.nojekyll
          make gendoc
          make mkd-gh-deploy
